version: '3.7'

services: 
  irisauth:
    build: 
      context: ./irisauth
      args:
        IMAGE: containers.intersystems.com/intersystems/iris:2023.1.0.229.0
        COMMIT_ID: ${COMMIT_ID}
    hostname: irisauth
    ports:
    - 52873:52773
    - 1972:1972
    command: --ISCAgent false --monitorCPF false --key /ISC/license/iris.key
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/ISC/cpf/merge1.cpf
    volumes:
    - .:/ISC

  irisrsc:
    build: 
      context: ./irisrsc
      args:
        IMAGE: containers.intersystems.com/intersystems/iris-community:2023.1.0.229.0
        COMMIT_ID: ${COMMIT_ID}
    hostname: irisrsc
    ports:
    - 52874:52773
    command: --ISCAgent false --monitorCPF false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/ISC/cpf/merge1.cpf
    volumes:
    - .:/ISC

  irisrsc2:
    build: 
      context: ./irisrsc
      args:
        IMAGE: containers.intersystems.com/intersystems/iris-community:2023.1.0.229.0
        COMMIT_ID: ${COMMIT_ID}
    hostname: irisrsc2
    ports:
    - 52875:52773
    command: --ISCAgent false --monitorCPF false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/ISC/cpf/merge1.cpf
    volumes:
    - .:/ISC
    
  irisclient:
    build: 
      context: ./irisclient
      args:
        IMAGE: containers.intersystems.com/intersystems/iris-community:2023.1.0.229.0
        COMMIT_ID: ${COMMIT_ID}
    hostname: irisclient
    ports:
    - 52876:52773
    command: --ISCAgent false --monitorCPF false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/ISC/cpf/merge1.cpf
    - OP=iris
    volumes:
    - .:/ISC

  webgw:
    build: 
      context: ./iris-webgateway-example
    init: true
    hostname: webgw.localdomain
    ports:
      - 80:80
      - 443:443
    environment: 
      TZ: JST-9
      SERVER_PORT: 1972
    volumes:
    - $PWD/htdocs:/usr/local/apache2/htdocs/ 
    - $PWD/apache-conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - $PWD/apache-conf/extra/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
    - $PWD/ssl/web/server.crt:/usr/local/apache2/conf/server.crt
    - $PWD/ssl/web/server.key:/usr/local/apache2/conf/server.key
    - $PWD/ssl/web/caint.crt:/usr/local/apache2/conf/server-ca.crt
    - $PWD/webgateway.conf:/opt/webgateway/apache/webgateway.conf

  iam-migrations:
    image: intersystems/iam:3.2.1.0-4
    command: bash -c "kong migrations bootstrap; kong migrations up; kong migrations finish"
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_CASSANDRA_CONTACT_POINTS: db
      ISC_IRIS_URL: IAM:SYS@irisauth:52773/api/iam/license 
      #ISC_CA_CERT: ${ISC_CA_CERT}
    restart: on-failure
    links:
      - db:db
  iam:
    image: intersystems/iam:3.2.1.0-4
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ANONYMOUS_REPORTS: 'off'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PORTAL: 'on'
      KONG_PORTAL_GUI_PROTOCOL: http
      KONG_PORTAL_GUI_HOST: '127.0.0.1:8003'
      KONG_ADMIN_GUI_URL: http://localhost:8002
      ISC_IRIS_URL: IAM:SYS@irisauth:52773/api/iam/license 
      #ISC_CA_CERT: ${ISC_CA_CERT}
    links:
      - db:db
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 8001
        published: 8001
        protocol: tcp
      - target: 8002
        published: 8002
        protocol: tcp
      - target: 8003
        published: 8003
        protocol: tcp
      - target: 8004
        published: 8004
        protocol: tcp
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 8444
        published: 8444
        protocol: tcp
      - target: 8445
        published: 8445
        protocol: tcp
    restart: on-failure
    #extra_hosts:
    #- WEBGW:${HOST_IP}

  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-iam}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      POSTGRES_USER: ${KONG_PG_USER:-iam}
    volumes:
      - 'pgdata14:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-iam}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    #tty: true
volumes:
  pgdata14:
